### ISSUE TITLE
Empty "palette" array.

### ISSUE THREAD

**Issue by przemyslawzaworski** [rkibria/img2shadertoy#1]
Python 3.6.6
Tested with Windows BMP files (resolution 64 and 128), generated code has always empty "palette" array:

const int[] palette = int[] (
);

**Comment by rkibria** [comment]
Is this a 24/32 bit color bitmap maybe? They aren't really supported at the moment but it should have thrown an error if you use them.

**Comment by przemyslawzaworski** [comment]
It was 8 bit color bitmap, but problem was related with BMPs saved from built-in Microsoft Paint. 
Bitmaps from GIMP work fine.

**Comment by rkibria** [comment]
I see. I think the BITMAPINFOHEADER structure might be changed then. My loader code is absolutely minimal and doesn't really deal well with anything except the most widespread format. I usually write BMP with Irfanview which I guess also writes the same format as GIMP. Should probably throw an error though if the palette is empty when it shouldn't be!
